/*
* generated by Xtext
*/
package net.sf.ubq.script.ui.contentassist.antlr;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

import net.sf.ubq.script.services.UbqtGrammarAccess;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

public class UbqtParser extends AbstractContentAssistParser {
	
	@Inject
	private UbqtGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected net.sf.ubq.script.ui.contentassist.antlr.internal.InternalUbqtParser createParser() {
		net.sf.ubq.script.ui.contentassist.antlr.internal.InternalUbqtParser result = new net.sf.ubq.script.ui.contentassist.antlr.internal.InternalUbqtParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getUbqCompositeAccess().getAlternatives_4(), "rule__UbqComposite__Alternatives_4");
					put(grammarAccess.getUbqCompositeAccess().getChildrenAlternatives_4_1_1_0(), "rule__UbqComposite__ChildrenAlternatives_4_1_1_0");
					put(grammarAccess.getUbqWidgetAccess().getAlternatives_0(), "rule__UbqWidget__Alternatives_0");
					put(grammarAccess.getUbqWidgetAccess().getStyleAlternatives_4_1_0(), "rule__UbqWidget__StyleAlternatives_4_1_0");
					put(grammarAccess.getUbqMenuAccess().getChildrenAlternatives_2_1_0(), "rule__UbqMenu__ChildrenAlternatives_2_1_0");
					put(grammarAccess.getSLOT_STATUSAccess().getAlternatives(), "rule__SLOT_STATUS__Alternatives");
					put(grammarAccess.getPROXIMA_STATUSAccess().getAlternatives(), "rule__PROXIMA_STATUS__Alternatives");
					put(grammarAccess.getSLOTSAccess().getAlternatives(), "rule__SLOTS__Alternatives");
					put(grammarAccess.getUBQ_LAYOUT_KINDAccess().getAlternatives(), "rule__UBQ_LAYOUT_KIND__Alternatives");
					put(grammarAccess.getUBQ_EVENTSAccess().getAlternatives(), "rule__UBQ_EVENTS__Alternatives");
					put(grammarAccess.getUBQ_GESTURESAccess().getAlternatives(), "rule__UBQ_GESTURES__Alternatives");
					put(grammarAccess.getFONT_STYLEAccess().getAlternatives(), "rule__FONT_STYLE__Alternatives");
					put(grammarAccess.getBORDER_STYLEAccess().getAlternatives(), "rule__BORDER_STYLE__Alternatives");
					put(grammarAccess.getDSLStrategyAccess().getAlternatives(), "rule__DSLStrategy__Alternatives");
					put(grammarAccess.getDSLRateAccess().getAlternatives(), "rule__DSLRate__Alternatives");
					put(grammarAccess.getDSLPriorityAccess().getAlternatives(), "rule__DSLPriority__Alternatives");
					put(grammarAccess.getUbqSessionAccess().getGroup(), "rule__UbqSession__Group__0");
					put(grammarAccess.getOrchestrorImportAccess().getGroup(), "rule__OrchestrorImport__Group__0");
					put(grammarAccess.getNetConfImportAccess().getGroup(), "rule__NetConfImport__Group__0");
					put(grammarAccess.getUbqDisplayModeAccess().getGroup(), "rule__UbqDisplayMode__Group__0");
					put(grammarAccess.getUbqActionAccess().getGroup(), "rule__UbqAction__Group__0");
					put(grammarAccess.getUbqActionAccess().getGroup_4(), "rule__UbqAction__Group_4__0");
					put(grammarAccess.getUbqActionAccess().getGroup_5(), "rule__UbqAction__Group_5__0");
					put(grammarAccess.getUbqActionAccess().getGroup_5_2(), "rule__UbqAction__Group_5_2__0");
					put(grammarAccess.getUbqReactionAccess().getGroup(), "rule__UbqReaction__Group__0");
					put(grammarAccess.getUbqReactionAccess().getGroup_4(), "rule__UbqReaction__Group_4__0");
					put(grammarAccess.getUbqFiducialAccess().getGroup(), "rule__UbqFiducial__Group__0");
					put(grammarAccess.getUbqProximaAccess().getGroup(), "rule__UbqProxima__Group__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_8(), "rule__UbqProxima__Group_8__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_9(), "rule__UbqProxima__Group_9__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_10(), "rule__UbqProxima__Group_10__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_11(), "rule__UbqProxima__Group_11__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_12(), "rule__UbqProxima__Group_12__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_12_2(), "rule__UbqProxima__Group_12_2__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_13(), "rule__UbqProxima__Group_13__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_13_1(), "rule__UbqProxima__Group_13_1__0");
					put(grammarAccess.getUbqProximaAccess().getGroup_13_1_1(), "rule__UbqProxima__Group_13_1_1__0");
					put(grammarAccess.getUbqHandledReactionsAccess().getGroup(), "rule__UbqHandledReactions__Group__0");
					put(grammarAccess.getUbqHandledReactionsAccess().getGroup_2(), "rule__UbqHandledReactions__Group_2__0");
					put(grammarAccess.getUbqHandledReactionsAccess().getGroup_3(), "rule__UbqHandledReactions__Group_3__0");
					put(grammarAccess.getUbqHandledReactionsAccess().getGroup_3_2(), "rule__UbqHandledReactions__Group_3_2__0");
					put(grammarAccess.getUbqEmmitedActionsAccess().getGroup(), "rule__UbqEmmitedActions__Group__0");
					put(grammarAccess.getUbqEmmitedActionsAccess().getGroup_2(), "rule__UbqEmmitedActions__Group_2__0");
					put(grammarAccess.getUbqEmmitedActionsAccess().getGroup_5(), "rule__UbqEmmitedActions__Group_5__0");
					put(grammarAccess.getUbqEmmitedActionsAccess().getGroup_6(), "rule__UbqEmmitedActions__Group_6__0");
					put(grammarAccess.getUbqEmmitedActionsAccess().getGroup_6_2(), "rule__UbqEmmitedActions__Group_6_2__0");
					put(grammarAccess.getUbqSlotAccess().getGroup(), "rule__UbqSlot__Group__0");
					put(grammarAccess.getUbqSlotAccess().getGroup_9(), "rule__UbqSlot__Group_9__0");
					put(grammarAccess.getUbqLayoutAccess().getGroup(), "rule__UbqLayout__Group__0");
					put(grammarAccess.getUbqCursorAccess().getGroup(), "rule__UbqCursor__Group__0");
					put(grammarAccess.getUbqCompositeAccess().getGroup(), "rule__UbqComposite__Group__0");
					put(grammarAccess.getUbqCompositeAccess().getGroup_4_1(), "rule__UbqComposite__Group_4_1__0");
					put(grammarAccess.getUbqPointAccess().getGroup(), "rule__UbqPoint__Group__0");
					put(grammarAccess.getUbqBoundsAccess().getGroup(), "rule__UbqBounds__Group__0");
					put(grammarAccess.getUbqWidgetAccess().getGroup(), "rule__UbqWidget__Group__0");
					put(grammarAccess.getUbqWidgetAccess().getGroup_1(), "rule__UbqWidget__Group_1__0");
					put(grammarAccess.getUbqWidgetAccess().getGroup_3(), "rule__UbqWidget__Group_3__0");
					put(grammarAccess.getUbqWidgetAccess().getGroup_4(), "rule__UbqWidget__Group_4__0");
					put(grammarAccess.getUbqWidgetAccess().getGroup_5(), "rule__UbqWidget__Group_5__0");
					put(grammarAccess.getUbqImageAccess().getGroup(), "rule__UbqImage__Group__0");
					put(grammarAccess.getUbqButtonAccess().getGroup(), "rule__UbqButton__Group__0");
					put(grammarAccess.getUbqButtonAccess().getGroup_2(), "rule__UbqButton__Group_2__0");
					put(grammarAccess.getUbqButtonAccess().getGroup_3(), "rule__UbqButton__Group_3__0");
					put(grammarAccess.getUbqLabelAccess().getGroup(), "rule__UbqLabel__Group__0");
					put(grammarAccess.getUbqCheckboxAccess().getGroup(), "rule__UbqCheckbox__Group__0");
					put(grammarAccess.getUbqTextAccess().getGroup(), "rule__UbqText__Group__0");
					put(grammarAccess.getUbqMenuAccess().getGroup(), "rule__UbqMenu__Group__0");
					put(grammarAccess.getUbqMenuAccess().getGroup_2(), "rule__UbqMenu__Group_2__0");
					put(grammarAccess.getUbqMenuItemAccess().getGroup(), "rule__UbqMenuItem__Group__0");
					put(grammarAccess.getUbqMenuItemAccess().getGroup_4(), "rule__UbqMenuItem__Group_4__0");
					put(grammarAccess.getUbqIncrementableRangeAccess().getGroup(), "rule__UbqIncrementableRange__Group__0");
					put(grammarAccess.getUbqIncrementableRangeAccess().getGroup_4(), "rule__UbqIncrementableRange__Group_4__0");
					put(grammarAccess.getUbqVuMeterAccess().getGroup(), "rule__UbqVuMeter__Group__0");
					put(grammarAccess.getUbqSpinnerAccess().getGroup(), "rule__UbqSpinner__Group__0");
					put(grammarAccess.getUbqSliderAccess().getGroup(), "rule__UbqSlider__Group__0");
					put(grammarAccess.getUbqKnobAccess().getGroup(), "rule__UbqKnob__Group__0");
					put(grammarAccess.getUbqWidgetStyleAccess().getGroup(), "rule__UbqWidgetStyle__Group__0");
					put(grammarAccess.getUbqColorStyleAccess().getGroup(), "rule__UbqColorStyle__Group__0");
					put(grammarAccess.getUbqColorStyleAccess().getGroup_1(), "rule__UbqColorStyle__Group_1__0");
					put(grammarAccess.getUbqColorStyleAccess().getGroup_2(), "rule__UbqColorStyle__Group_2__0");
					put(grammarAccess.getUbqFontStyleAccess().getGroup(), "rule__UbqFontStyle__Group__0");
					put(grammarAccess.getUbqFontStyleAccess().getGroup_1(), "rule__UbqFontStyle__Group_1__0");
					put(grammarAccess.getUbqFontStyleAccess().getGroup_2(), "rule__UbqFontStyle__Group_2__0");
					put(grammarAccess.getUbqFontStyleAccess().getGroup_3(), "rule__UbqFontStyle__Group_3__0");
					put(grammarAccess.getUbqFontStyleAccess().getGroup_3_2(), "rule__UbqFontStyle__Group_3_2__0");
					put(grammarAccess.getUbqBorderStyleAccess().getGroup(), "rule__UbqBorderStyle__Group__0");
					put(grammarAccess.getUbqBorderStyleAccess().getGroup_1(), "rule__UbqBorderStyle__Group_1__0");
					put(grammarAccess.getUbqBorderStyleAccess().getGroup_2(), "rule__UbqBorderStyle__Group_2__0");
					put(grammarAccess.getUbqBorderStyleAccess().getGroup_2_2(), "rule__UbqBorderStyle__Group_2_2__0");
					put(grammarAccess.getUbqHsbColorAccess().getGroup(), "rule__UbqHsbColor__Group__0");
					put(grammarAccess.getUbqRgbColorAccess().getGroup(), "rule__UbqRgbColor__Group__0");
					put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
					put(grammarAccess.getFloatAccess().getGroup_1(), "rule__Float__Group_1__0");
					put(grammarAccess.getDSLOrchestrorAccess().getGroup(), "rule__DSLOrchestror__Group__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup(), "rule__DSLCommandEngine__Group__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_2(), "rule__DSLCommandEngine__Group_2__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_3(), "rule__DSLCommandEngine__Group_3__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_4(), "rule__DSLCommandEngine__Group_4__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_5(), "rule__DSLCommandEngine__Group_5__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_6(), "rule__DSLCommandEngine__Group_6__0");
					put(grammarAccess.getDSLCommandEngineAccess().getGroup_7(), "rule__DSLCommandEngine__Group_7__0");
					put(grammarAccess.getDSLEngineClientAccess().getGroup(), "rule__DSLEngineClient__Group__0");
					put(grammarAccess.getDSLEngineClientAccess().getGroup_2(), "rule__DSLEngineClient__Group_2__0");
					put(grammarAccess.getUbqSessionAccess().getNetconfsAssignment_0(), "rule__UbqSession__NetconfsAssignment_0");
					put(grammarAccess.getUbqSessionAccess().getOrchestrorsAssignment_1(), "rule__UbqSession__OrchestrorsAssignment_1");
					put(grammarAccess.getUbqSessionAccess().getDisplayModeAssignment_2(), "rule__UbqSession__DisplayModeAssignment_2");
					put(grammarAccess.getUbqSessionAccess().getFiducialsAssignment_3(), "rule__UbqSession__FiducialsAssignment_3");
					put(grammarAccess.getUbqSessionAccess().getActionsAssignment_4(), "rule__UbqSession__ActionsAssignment_4");
					put(grammarAccess.getUbqSessionAccess().getReactionsAssignment_5(), "rule__UbqSession__ReactionsAssignment_5");
					put(grammarAccess.getUbqSessionAccess().getEmmitersAssignment_6(), "rule__UbqSession__EmmitersAssignment_6");
					put(grammarAccess.getUbqSessionAccess().getHandlersAssignment_7(), "rule__UbqSession__HandlersAssignment_7");
					put(grammarAccess.getUbqSessionAccess().getSlotsAssignment_8(), "rule__UbqSession__SlotsAssignment_8");
					put(grammarAccess.getUbqSessionAccess().getProximiAssignment_9(), "rule__UbqSession__ProximiAssignment_9");
					put(grammarAccess.getUbqSessionAccess().getFingersAssignment_10(), "rule__UbqSession__FingersAssignment_10");
					put(grammarAccess.getOrchestrorImportAccess().getImportURIAssignment_1(), "rule__OrchestrorImport__ImportURIAssignment_1");
					put(grammarAccess.getNetConfImportAccess().getImportURIAssignment_1(), "rule__NetConfImport__ImportURIAssignment_1");
					put(grammarAccess.getUbqDisplayModeAccess().getModeAssignment_1(), "rule__UbqDisplayMode__ModeAssignment_1");
					put(grammarAccess.getUbqActionAccess().getNameAssignment_1(), "rule__UbqAction__NameAssignment_1");
					put(grammarAccess.getUbqActionAccess().getActionIDsAssignment_3(), "rule__UbqAction__ActionIDsAssignment_3");
					put(grammarAccess.getUbqActionAccess().getActionIDsAssignment_4_1(), "rule__UbqAction__ActionIDsAssignment_4_1");
					put(grammarAccess.getUbqActionAccess().getArgsAssignment_5_1(), "rule__UbqAction__ArgsAssignment_5_1");
					put(grammarAccess.getUbqActionAccess().getArgsAssignment_5_2_1(), "rule__UbqAction__ArgsAssignment_5_2_1");
					put(grammarAccess.getUbqReactionAccess().getNameAssignment_1(), "rule__UbqReaction__NameAssignment_1");
					put(grammarAccess.getUbqReactionAccess().getCmdIDsAssignment_3(), "rule__UbqReaction__CmdIDsAssignment_3");
					put(grammarAccess.getUbqReactionAccess().getCmdIDsAssignment_4_1(), "rule__UbqReaction__CmdIDsAssignment_4_1");
					put(grammarAccess.getUbqReactionAccess().getClazzAssignment_6(), "rule__UbqReaction__ClazzAssignment_6");
					put(grammarAccess.getUbqFiducialAccess().getNameAssignment_1(), "rule__UbqFiducial__NameAssignment_1");
					put(grammarAccess.getUbqFiducialAccess().getFidcodeAssignment_3(), "rule__UbqFiducial__FidcodeAssignment_3");
					put(grammarAccess.getUbqProximaAccess().getNameAssignment_1(), "rule__UbqProxima__NameAssignment_1");
					put(grammarAccess.getUbqProximaAccess().getFiducialAssignment_3(), "rule__UbqProxima__FiducialAssignment_3");
					put(grammarAccess.getUbqProximaAccess().getEngineAssignment_5(), "rule__UbqProxima__EngineAssignment_5");
					put(grammarAccess.getUbqProximaAccess().getRangeAssignment_7(), "rule__UbqProxima__RangeAssignment_7");
					put(grammarAccess.getUbqProximaAccess().getBoundsAssignment_8_1(), "rule__UbqProxima__BoundsAssignment_8_1");
					put(grammarAccess.getUbqProximaAccess().getRadiusAssignment_9_1(), "rule__UbqProxima__RadiusAssignment_9_1");
					put(grammarAccess.getUbqProximaAccess().getAngleAssignment_10_1(), "rule__UbqProxima__AngleAssignment_10_1");
					put(grammarAccess.getUbqProximaAccess().getStatusAssignment_11_1(), "rule__UbqProxima__StatusAssignment_11_1");
					put(grammarAccess.getUbqProximaAccess().getRequiredProximiAssignment_12_1(), "rule__UbqProxima__RequiredProximiAssignment_12_1");
					put(grammarAccess.getUbqProximaAccess().getRequiredProximiAssignment_12_2_1(), "rule__UbqProxima__RequiredProximiAssignment_12_2_1");
					put(grammarAccess.getUbqProximaAccess().getSlotsAssignment_13_1_0(), "rule__UbqProxima__SlotsAssignment_13_1_0");
					put(grammarAccess.getUbqProximaAccess().getSlotsAssignment_13_1_1_1(), "rule__UbqProxima__SlotsAssignment_13_1_1_1");
					put(grammarAccess.getUbqProximaAccess().getEmittedAssignment_13_2(), "rule__UbqProxima__EmittedAssignment_13_2");
					put(grammarAccess.getUbqProximaAccess().getReactedAssignment_13_3(), "rule__UbqProxima__ReactedAssignment_13_3");
					put(grammarAccess.getUbqHandledReactionsAccess().getReactionsAssignment_1(), "rule__UbqHandledReactions__ReactionsAssignment_1");
					put(grammarAccess.getUbqHandledReactionsAccess().getReactionsAssignment_2_1(), "rule__UbqHandledReactions__ReactionsAssignment_2_1");
					put(grammarAccess.getUbqHandledReactionsAccess().getProximiAsRefAssignment_3_1(), "rule__UbqHandledReactions__ProximiAsRefAssignment_3_1");
					put(grammarAccess.getUbqHandledReactionsAccess().getProximiAsRefAssignment_3_2_1(), "rule__UbqHandledReactions__ProximiAsRefAssignment_3_2_1");
					put(grammarAccess.getUbqEmmitedActionsAccess().getActionsAssignment_1(), "rule__UbqEmmitedActions__ActionsAssignment_1");
					put(grammarAccess.getUbqEmmitedActionsAccess().getActionsAssignment_2_1(), "rule__UbqEmmitedActions__ActionsAssignment_2_1");
					put(grammarAccess.getUbqEmmitedActionsAccess().getEventsAssignment_4(), "rule__UbqEmmitedActions__EventsAssignment_4");
					put(grammarAccess.getUbqEmmitedActionsAccess().getEventsAssignment_5_1(), "rule__UbqEmmitedActions__EventsAssignment_5_1");
					put(grammarAccess.getUbqEmmitedActionsAccess().getProximiAsRefAssignment_6_1(), "rule__UbqEmmitedActions__ProximiAsRefAssignment_6_1");
					put(grammarAccess.getUbqEmmitedActionsAccess().getProximiAsRefAssignment_6_2_1(), "rule__UbqEmmitedActions__ProximiAsRefAssignment_6_2_1");
					put(grammarAccess.getUbqSlotAccess().getNameAssignment_1(), "rule__UbqSlot__NameAssignment_1");
					put(grammarAccess.getUbqSlotAccess().getBoundsAssignment_2(), "rule__UbqSlot__BoundsAssignment_2");
					put(grammarAccess.getUbqSlotAccess().getPositionAssignment_4(), "rule__UbqSlot__PositionAssignment_4");
					put(grammarAccess.getUbqSlotAccess().getKindAssignment_6(), "rule__UbqSlot__KindAssignment_6");
					put(grammarAccess.getUbqSlotAccess().getStatusAssignment_8(), "rule__UbqSlot__StatusAssignment_8");
					put(grammarAccess.getUbqSlotAccess().getEmittedAssignment_9_1(), "rule__UbqSlot__EmittedAssignment_9_1");
					put(grammarAccess.getUbqSlotAccess().getReactedAssignment_9_2(), "rule__UbqSlot__ReactedAssignment_9_2");
					put(grammarAccess.getUbqLayoutAccess().getKindAssignment_1(), "rule__UbqLayout__KindAssignment_1");
					put(grammarAccess.getUbqCursorAccess().getNameAssignment_1(), "rule__UbqCursor__NameAssignment_1");
					put(grammarAccess.getUbqCursorAccess().getPosAssignment_2(), "rule__UbqCursor__PosAssignment_2");
					put(grammarAccess.getUbqCursorAccess().getDimAssignment_4(), "rule__UbqCursor__DimAssignment_4");
					put(grammarAccess.getUbqCompositeAccess().getNameAssignment_1(), "rule__UbqComposite__NameAssignment_1");
					put(grammarAccess.getUbqCompositeAccess().getBoundsAssignment_2(), "rule__UbqComposite__BoundsAssignment_2");
					put(grammarAccess.getUbqCompositeAccess().getLayoutAssignment_3(), "rule__UbqComposite__LayoutAssignment_3");
					put(grammarAccess.getUbqCompositeAccess().getChildrenAssignment_4_1_1(), "rule__UbqComposite__ChildrenAssignment_4_1_1");
					put(grammarAccess.getUbqPointAccess().getXAssignment_1(), "rule__UbqPoint__XAssignment_1");
					put(grammarAccess.getUbqPointAccess().getYAssignment_3(), "rule__UbqPoint__YAssignment_3");
					put(grammarAccess.getUbqBoundsAccess().getXAssignment_1(), "rule__UbqBounds__XAssignment_1");
					put(grammarAccess.getUbqBoundsAccess().getYAssignment_3(), "rule__UbqBounds__YAssignment_3");
					put(grammarAccess.getUbqBoundsAccess().getWidthAssignment_5(), "rule__UbqBounds__WidthAssignment_5");
					put(grammarAccess.getUbqBoundsAccess().getHeightAssignment_7(), "rule__UbqBounds__HeightAssignment_7");
					put(grammarAccess.getUbqWidgetAccess().getParentAssignment_1_1(), "rule__UbqWidget__ParentAssignment_1_1");
					put(grammarAccess.getUbqWidgetAccess().getBoundsAssignment_2(), "rule__UbqWidget__BoundsAssignment_2");
					put(grammarAccess.getUbqWidgetAccess().getAngleAssignment_3_1(), "rule__UbqWidget__AngleAssignment_3_1");
					put(grammarAccess.getUbqWidgetAccess().getStyleAssignment_4_1(), "rule__UbqWidget__StyleAssignment_4_1");
					put(grammarAccess.getUbqWidgetAccess().getEmittedAssignment_5_1(), "rule__UbqWidget__EmittedAssignment_5_1");
					put(grammarAccess.getUbqWidgetAccess().getReactedAssignment_5_2(), "rule__UbqWidget__ReactedAssignment_5_2");
					put(grammarAccess.getUbqImageAccess().getNameAssignment_1(), "rule__UbqImage__NameAssignment_1");
					put(grammarAccess.getUbqImageAccess().getImageAssignment_3(), "rule__UbqImage__ImageAssignment_3");
					put(grammarAccess.getUbqButtonAccess().getNameAssignment_1(), "rule__UbqButton__NameAssignment_1");
					put(grammarAccess.getUbqButtonAccess().getTextAssignment_2_1(), "rule__UbqButton__TextAssignment_2_1");
					put(grammarAccess.getUbqButtonAccess().getImageAssignment_3_1(), "rule__UbqButton__ImageAssignment_3_1");
					put(grammarAccess.getUbqLabelAccess().getNameAssignment_1(), "rule__UbqLabel__NameAssignment_1");
					put(grammarAccess.getUbqLabelAccess().getTextAssignment_3(), "rule__UbqLabel__TextAssignment_3");
					put(grammarAccess.getUbqCheckboxAccess().getNameAssignment_1(), "rule__UbqCheckbox__NameAssignment_1");
					put(grammarAccess.getUbqCheckboxAccess().getCheckedAssignment_2(), "rule__UbqCheckbox__CheckedAssignment_2");
					put(grammarAccess.getUbqTextAccess().getNameAssignment_1(), "rule__UbqText__NameAssignment_1");
					put(grammarAccess.getUbqTextAccess().getTextAssignment_3(), "rule__UbqText__TextAssignment_3");
					put(grammarAccess.getUbqMenuAccess().getNameAssignment_1(), "rule__UbqMenu__NameAssignment_1");
					put(grammarAccess.getUbqMenuAccess().getChildrenAssignment_2_1(), "rule__UbqMenu__ChildrenAssignment_2_1");
					put(grammarAccess.getUbqMenuItemAccess().getNameAssignment_1(), "rule__UbqMenuItem__NameAssignment_1");
					put(grammarAccess.getUbqMenuItemAccess().getTitleAssignment_3(), "rule__UbqMenuItem__TitleAssignment_3");
					put(grammarAccess.getUbqMenuItemAccess().getEmittedAssignment_4_1(), "rule__UbqMenuItem__EmittedAssignment_4_1");
					put(grammarAccess.getUbqIncrementableRangeAccess().getMinAssignment_1(), "rule__UbqIncrementableRange__MinAssignment_1");
					put(grammarAccess.getUbqIncrementableRangeAccess().getMaxAssignment_3(), "rule__UbqIncrementableRange__MaxAssignment_3");
					put(grammarAccess.getUbqIncrementableRangeAccess().getValAssignment_4_1(), "rule__UbqIncrementableRange__ValAssignment_4_1");
					put(grammarAccess.getUbqVuMeterAccess().getNameAssignment_1(), "rule__UbqVuMeter__NameAssignment_1");
					put(grammarAccess.getUbqVuMeterAccess().getRangeDefinitionAssignment_2(), "rule__UbqVuMeter__RangeDefinitionAssignment_2");
					put(grammarAccess.getUbqSpinnerAccess().getNameAssignment_1(), "rule__UbqSpinner__NameAssignment_1");
					put(grammarAccess.getUbqSpinnerAccess().getRangeDefinitionAssignment_2(), "rule__UbqSpinner__RangeDefinitionAssignment_2");
					put(grammarAccess.getUbqSliderAccess().getNameAssignment_1(), "rule__UbqSlider__NameAssignment_1");
					put(grammarAccess.getUbqSliderAccess().getRangeDefinitionAssignment_2(), "rule__UbqSlider__RangeDefinitionAssignment_2");
					put(grammarAccess.getUbqKnobAccess().getNameAssignment_1(), "rule__UbqKnob__NameAssignment_1");
					put(grammarAccess.getUbqKnobAccess().getRangeDefinitionAssignment_2(), "rule__UbqKnob__RangeDefinitionAssignment_2");
					put(grammarAccess.getUbqWidgetStyleAccess().getColorStyleAssignment_1(), "rule__UbqWidgetStyle__ColorStyleAssignment_1");
					put(grammarAccess.getUbqWidgetStyleAccess().getFontStyleStyleAssignment_2(), "rule__UbqWidgetStyle__FontStyleStyleAssignment_2");
					put(grammarAccess.getUbqWidgetStyleAccess().getBorderStyleAssignment_3(), "rule__UbqWidgetStyle__BorderStyleAssignment_3");
					put(grammarAccess.getUbqColorStyleAccess().getForegroundAssignment_1_1(), "rule__UbqColorStyle__ForegroundAssignment_1_1");
					put(grammarAccess.getUbqColorStyleAccess().getBackgroundAssignment_2_1(), "rule__UbqColorStyle__BackgroundAssignment_2_1");
					put(grammarAccess.getUbqFontStyleAccess().getFontAssignment_1_1(), "rule__UbqFontStyle__FontAssignment_1_1");
					put(grammarAccess.getUbqFontStyleAccess().getHeightAssignment_2_1(), "rule__UbqFontStyle__HeightAssignment_2_1");
					put(grammarAccess.getUbqFontStyleAccess().getStylesAssignment_3_1(), "rule__UbqFontStyle__StylesAssignment_3_1");
					put(grammarAccess.getUbqFontStyleAccess().getStylesAssignment_3_2_1(), "rule__UbqFontStyle__StylesAssignment_3_2_1");
					put(grammarAccess.getUbqBorderStyleAccess().getTicknessAssignment_1_1(), "rule__UbqBorderStyle__TicknessAssignment_1_1");
					put(grammarAccess.getUbqBorderStyleAccess().getStylesAssignment_2_1(), "rule__UbqBorderStyle__StylesAssignment_2_1");
					put(grammarAccess.getUbqBorderStyleAccess().getStylesAssignment_2_2_1(), "rule__UbqBorderStyle__StylesAssignment_2_2_1");
					put(grammarAccess.getUbqHsbColorAccess().getHueAssignment_2(), "rule__UbqHsbColor__HueAssignment_2");
					put(grammarAccess.getUbqHsbColorAccess().getSaturationAssignment_4(), "rule__UbqHsbColor__SaturationAssignment_4");
					put(grammarAccess.getUbqHsbColorAccess().getBrightnessAssignment_6(), "rule__UbqHsbColor__BrightnessAssignment_6");
					put(grammarAccess.getUbqRgbColorAccess().getRedAssignment_2(), "rule__UbqRgbColor__RedAssignment_2");
					put(grammarAccess.getUbqRgbColorAccess().getGreenAssignment_4(), "rule__UbqRgbColor__GreenAssignment_4");
					put(grammarAccess.getUbqRgbColorAccess().getBlueAssignment_6(), "rule__UbqRgbColor__BlueAssignment_6");
					put(grammarAccess.getDSLOrchestrorAccess().getNameAssignment_1(), "rule__DSLOrchestror__NameAssignment_1");
					put(grammarAccess.getDSLOrchestrorAccess().getEnginesAssignment_3(), "rule__DSLOrchestror__EnginesAssignment_3");
					put(grammarAccess.getDSLOrchestrorAccess().getClientsAssignment_4(), "rule__DSLOrchestror__ClientsAssignment_4");
					put(grammarAccess.getDSLCommandEngineAccess().getNameAssignment_1(), "rule__DSLCommandEngine__NameAssignment_1");
					put(grammarAccess.getDSLCommandEngineAccess().getSpeedAssignment_2_1(), "rule__DSLCommandEngine__SpeedAssignment_2_1");
					put(grammarAccess.getDSLCommandEngineAccess().getTtlAssignment_3_1(), "rule__DSLCommandEngine__TtlAssignment_3_1");
					put(grammarAccess.getDSLCommandEngineAccess().getStrategyAssignment_4_1(), "rule__DSLCommandEngine__StrategyAssignment_4_1");
					put(grammarAccess.getDSLCommandEngineAccess().getThresholdAssignment_5_1(), "rule__DSLCommandEngine__ThresholdAssignment_5_1");
					put(grammarAccess.getDSLCommandEngineAccess().getPriorityAssignment_6_1(), "rule__DSLCommandEngine__PriorityAssignment_6_1");
					put(grammarAccess.getDSLCommandEngineAccess().getFillterIDAssignment_7_1(), "rule__DSLCommandEngine__FillterIDAssignment_7_1");
					put(grammarAccess.getDSLEngineClientAccess().getNameAssignment_1(), "rule__DSLEngineClient__NameAssignment_1");
					put(grammarAccess.getDSLEngineClientAccess().getSpeedAssignment_2_1(), "rule__DSLEngineClient__SpeedAssignment_2_1");
					put(grammarAccess.getDSLEngineClientAccess().getRefCmdEnginesAssignment_4(), "rule__DSLEngineClient__RefCmdEnginesAssignment_4");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			net.sf.ubq.script.ui.contentassist.antlr.internal.InternalUbqtParser typedParser = (net.sf.ubq.script.ui.contentassist.antlr.internal.InternalUbqtParser) parser;
			typedParser.entryRuleUbqSession();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public UbqtGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(UbqtGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
