
/*
 * generated by Xtext
 */
 
package net.sf.ubq.script.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class UbqtExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return net.sf.ubq.script.ui.internal.UbqtActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return net.sf.ubq.script.ui.internal.UbqtActivator.getInstance().getInjector("net.sf.ubq.script.Ubqt");
	}
	
}
